name: Build and push Docker image to GitHub Packages

on:
  workflow_dispatch: # allows manual triggering
  push:
    branches:
      - main
  
env:
  IMAGE_NAME: bedrockconnectserver
  DOCKERFILE_PATH: Dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ${{ env.DOCKERFILE_PATH }}
        push: true
        tags: ghcr.io/rsereno/${{ env.IMAGE_NAME }}:latest, ghcr.io/rsereno/${{ env.IMAGE_NAME }}:${{ github.sha }}
